INSERT INTO tb_category(name, created_At) VALUES ('Alimentos & Bebidas',now()) ;
INSERT INTO tb_category(name, created_At) VALUES ('App e Jogos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Automotivos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Bebês',now());
INSERT INTO tb_category(name, created_At) VALUES ('Beleza',now());
INSERT INTO tb_category(name, created_At) VALUES ('Bolsas, Malas e Mochilas',now());
INSERT INTO tb_category(name, created_At) VALUES ('Brinquedos e Jogos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Casas',now());
INSERT INTO tb_category(name, created_At) VALUES ('Computadores e Informática',now());
INSERT INTO tb_category(name, created_At) VALUES ('Cozinhas',now());
INSERT INTO tb_category(name, created_At) VALUES ('Dispositivos',now());
INSERT INTO tb_category(name, created_At) VALUES ('DVD e Blu-Ray',now());
INSERT INTO tb_category(name, created_At) VALUES ('Eletrodomésticos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Eletrônicos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Esporte e Aventura',now());
INSERT INTO tb_category(name, created_At) VALUES ('Ferramentas e Materias para Construção',now());
INSERT INTO tb_category(name, created_At) VALUES ('Games',now());
INSERT INTO tb_category(name, created_At) VALUES ('Instrumentos musicais',now());
INSERT INTO tb_category(name, created_At) VALUES ('Jardim e Piscinas',now());
INSERT INTO tb_category(name, created_At) VALUES ('Livros',now());
INSERT INTO tb_category(name, created_At) VALUES ('Instrumentos musicais',now());
INSERT INTO tb_category(name, created_At) VALUES ('Materiais para Escritório e Papelaria',now());
INSERT INTO tb_category(name, created_At) VALUES ('Moveis e Decoração',now());
INSERT INTO tb_category(name, created_At) VALUES ('PetShop',now());
INSERT INTO tb_category(name, created_At) VALUES ('Roupa Calçados e Joias',now());
INSERT INTO tb_category(name, created_At) VALUES ('Saúde e Cuidados Pessoais',now());
INSERT INTO tb_category(name, created_At) VALUES ('TV e Videos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Telefones e Celulares',now());
INSERT INTO tb_category(name, created_At) VALUES ('Utilidades Domesticas',now());
INSERT INTO tb_category(name, created_At) VALUES ('Serviços',now());
INSERT INTO tb_category(name, created_At) VALUES ('Perfumárias e Comesticos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Eletroportatil',now());
INSERT INTO tb_category(name, created_At) VALUES ('Perfumárias e Comesticos',now());
INSERT INTO tb_category(name, created_At) VALUES ('Esporte e Lazer',now());
INSERT INTO tb_category(name, created_At) VALUES ('Ferramentas',now());
INSERT INTO tb_category(name, created_At) VALUES ('Drones, Cameras e Filmadoras',now());
